### PR TITLE
dispose of opened socket

### PR DESCRIPTION
**Pull request by jchannon**
seems to solve #28

### CODE REVIEW

**Comment by Bobris** [comment]
I know about this bug in Mono it does not correctly implement:
            _disconnectEvent.DisconnectReuseSocket = true;

On .Net it correctly reuse socket, so it saves some allocations and OS calls. I would accept it if you check for environment type and did it only on Mono.

I still hope that someone will implement correct and optimal Saea implementation for Linux.

**Comment by jchannon** [comment]
Do you have any #if mono directives already setup?

**Comment by jchannon** [comment]
Do you have any `#if mono` directives already setup?

If not would you be happy if I added them and would I set `_disconnectEvent.DisconnectReuseSocket = false;` as well as the socket.Dispose already in this PR?

**Comment by Bobris** [comment]
I though about not doing it by #if directives but by checking "something" at runtime, so you don't need to recompile .dll you get from Nuget.

     public static bool IsRunningOnMono ()
     {
          return Type.GetType ("Mono.Runtime") != null;
     }

**Comment by jchannon** [comment]
Sure I can add that.

Do I just need to set that boolean value to false and dispose of the socket
after that?

**Comment by Bobris** [comment]
Set all 3:

            _receiveEvent.DisconnectReuseSocket = true;
            _sendEvent.DisconnectReuseSocket = true;
            _disconnectEvent.DisconnectReuseSocket = true;

To false already in void RecreateSaeas(), based on running on Mono. Maybe even name it "does not support DisconnectReuseSocket"

**Comment by jchannon** [comment]
Thanks. I've updated the PR

**Comment by jchannon** [comment]
Looks like as the PR is closed you cant see the changes in the diff

**Comment by Bobris** [comment]
Reopened, but still don't see anything.

**Comment by jchannon** [comment]
Should be there now :smile:

**Comment by Bobris** [comment]
I will polish it a little bit. And build new version after that.

**Comment by jchannon** [comment]
Thanks, appreciate it!

**Comment by Bobris** [comment]
Done, please test.

**Comment by jchannon** [comment]
Left an update on #28

**Pull request merged**
